dvwa:
  build: .
  dockerfile: Dockerfile.webserver
  links:
    - dvwamysql:dvwamysql
  ports:
    - 8080:80
  volumes_from:
    - dvwacontent

dvwacontent:
  build: .
  dockerfile: Dockerfile.content
  command: /bin/sh -c 'true'

dvwamysql:
  image: mysql:5.6.27
  environment:
  -  MYSQL_ROOT_PASSWORD=p@ssw0rd
